plugins {
    id 'java'
}

group = 'me.saminasian'
version = '1.5.2-1.21.11'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

jar {
    archiveBaseName = 'MogRitual'
    archiveVersion = '1.5.2-Leaf-1.21.11'
}
